# Field ID
FIELD_NOTHING = 0
FIELD_WARSHIP = 1
FIELD_DESTROYER = 2
FIELD_SUBMARINE = 3

# connection status
CONNECTION_HOST_INIT_RESPONSE = 0
CONNECTION_HOST_SETTING = 1
CONNECTION_HOST_SETTING_RESPONSE = 2
CONNECTION_START = 3
CONNECTION_START_RESPONSE = 4
CONNECTION_SHIP_INIT_START = 5
CONNECTION_SHIP_INIT =6
CONNECTION_BATTLE_START = 7
CONNECTION_BATTLE_PLAYER_CHANGE = 8
CONNECTION_PLAYER_ACTION = 9
CONNECTION_PLAYER_ACTION_RESPONSE = 10
CONNECTION_SEND_MESSAGE = 11
CONNECTION_ALIVE_MESSAGE = 12
CONNECTION_RESULT = 13
CONNECTION_NORMAL_INIT_RESPONSE = 14
CONNECTION_NORMAL_USER_SETTING = 15
CONNECTION_NORMAL_USER_SETTING_RESPONSE = 16
CONNECTION_SEND_PUBLIC_KEY = 17
CONNECTION_SEND_PUBLIC_KEY_RESPONSE = 18


# private key
PRIVATE_KEY = 'private_key'
